<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('audit_logs', function (Blueprint $table) {
            $table->id();

            // User who performed the action.
            // Nullable because some events may be generated by the system.
            $table->foreignId('user_id')
                ->nullable()
                ->constrained('users')
                ->nullOnDelete();

            // Actor information kept for readable historical logs.
            $table->string('actor_name')->nullable();
            $table->string('actor_username')->nullable();

            // Type of activity.
            $table->string('event_type', 50)->default('activity');

            // Short action identifier.
            $table->string('action', 100);

            // QRPass module where the activity happened.
            $table->string('module', 100)->nullable();

            // Human-readable description.
            $table->text('description');

            // Result of the action.
            $table->string('status', 30)->default('success');

            // Request/security information.
            $table->string('ip_address', 45)->nullable();
            $table->text('user_agent')->nullable();

            // Extra optional information about the event.
            $table->json('metadata')->nullable();

            $table->timestamps();

            // Helpful indexes for Audit Logs filtering.
            $table->index('event_type');
            $table->index('action');
            $table->index('status');
            $table->index('created_at');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('audit_logs');
    }
};